{
 "title": "OpenGNB",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(up{job=\"opengnb\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transmit Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(opengnb_network_transmit_bytes_total{instance=~\"$node:.+\"}[$__rate_interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Receive Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(opengnb_network_receive_bytes_total{instance=~\"$node:.+\"}[$__rate_interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Transmit Data Today",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(node) (increase(opengnb_network_transmit_bytes_total{instance=~\"$node:.+\"}[1d] offset -1d))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Receive Data Today",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (increase(opengnb_network_receive_bytes_total{instance=~\"$node:.+\"}[1d] offset -1d))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Reachability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "opengnb_node_state{instance=~\"$node:.+\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "IPv4 Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "opengnb_node_addr4_ping_latency_ms{instance=~\"$node:.+\"} > 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "IPv6 Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "opengnb_node_addr6_ping_latency_ms{instance=~\"$node:.+\"} > 0",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}